[Wed Sep 30 09:38:54.807255 2020] [wsgi:error] [pid 1722:tid 3013581632] [client 129.41.86.1:45545] mod_wsgi (pid=1722): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 09:38:54.807342 2020] [wsgi:error] [pid 1722:tid 3013581632] [client 129.41.86.1:45545] mod_wsgi (pid=1722): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 09:38:54.807385 2020] [wsgi:error] [pid 1722:tid 3013581632] [client 129.41.86.1:45545] Traceback (most recent call last):
[Wed Sep 30 09:38:54.807426 2020] [wsgi:error] [pid 1722:tid 3013581632] [client 129.41.86.1:45545]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 09:38:54.807520 2020] [wsgi:error] [pid 1722:tid 3013581632] [client 129.41.86.1:45545]     import cv2
[Wed Sep 30 09:38:54.807555 2020] [wsgi:error] [pid 1722:tid 3013581632] [client 129.41.86.1:45545] ImportError: No module named cv2
[Wed Sep 30 10:55:49.513745 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 102.134.73.33:6107] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 10:55:49.513825 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 102.134.73.33:6107] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 10:55:49.513867 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 102.134.73.33:6107] Traceback (most recent call last):
[Wed Sep 30 10:55:49.513905 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 102.134.73.33:6107]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 10:55:49.513994 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 102.134.73.33:6107]     import cv2
[Wed Sep 30 10:55:49.514029 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 102.134.73.33:6107] ImportError: No module named cv2
[Wed Sep 30 10:58:57.753176 2020] [wsgi:error] [pid 1723:tid 3021974336] [client 193.174.89.19:48668] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 10:58:57.753280 2020] [wsgi:error] [pid 1723:tid 3021974336] [client 193.174.89.19:48668] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 10:58:57.753351 2020] [wsgi:error] [pid 1723:tid 3021974336] [client 193.174.89.19:48668] Traceback (most recent call last):
[Wed Sep 30 10:58:57.753421 2020] [wsgi:error] [pid 1723:tid 3021974336] [client 193.174.89.19:48668]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 10:58:57.753516 2020] [wsgi:error] [pid 1723:tid 3021974336] [client 193.174.89.19:48668]     import cv2
[Wed Sep 30 10:58:57.753580 2020] [wsgi:error] [pid 1723:tid 3021974336] [client 193.174.89.19:48668] ImportError: No module named cv2
[Wed Sep 30 11:27:22.941811 2020] [wsgi:error] [pid 1723:tid 2980010816] [client 80.82.77.240:64344] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 11:27:22.941913 2020] [wsgi:error] [pid 1723:tid 2980010816] [client 80.82.77.240:64344] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 11:27:22.941983 2020] [wsgi:error] [pid 1723:tid 2980010816] [client 80.82.77.240:64344] Traceback (most recent call last):
[Wed Sep 30 11:27:22.942053 2020] [wsgi:error] [pid 1723:tid 2980010816] [client 80.82.77.240:64344]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 11:27:22.942147 2020] [wsgi:error] [pid 1723:tid 2980010816] [client 80.82.77.240:64344]     import cv2
[Wed Sep 30 11:27:22.942212 2020] [wsgi:error] [pid 1723:tid 2980010816] [client 80.82.77.240:64344] ImportError: No module named cv2
[Wed Sep 30 11:32:00.748765 2020] [wsgi:error] [pid 1723:tid 2971618112] [client 77.49.230.7:59400] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 11:32:00.748897 2020] [wsgi:error] [pid 1723:tid 2971618112] [client 77.49.230.7:59400] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 11:32:00.748966 2020] [wsgi:error] [pid 1723:tid 2971618112] [client 77.49.230.7:59400] Traceback (most recent call last):
[Wed Sep 30 11:32:00.749035 2020] [wsgi:error] [pid 1723:tid 2971618112] [client 77.49.230.7:59400]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 11:32:00.749126 2020] [wsgi:error] [pid 1723:tid 2971618112] [client 77.49.230.7:59400]     import cv2
[Wed Sep 30 11:32:00.749187 2020] [wsgi:error] [pid 1723:tid 2971618112] [client 77.49.230.7:59400] ImportError: No module named cv2
[Wed Sep 30 11:49:34.563456 2020] [wsgi:error] [pid 1723:tid 3030367040] [client 192.227.223.108:443] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 11:49:34.563560 2020] [wsgi:error] [pid 1723:tid 3030367040] [client 192.227.223.108:443] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 11:49:34.563631 2020] [wsgi:error] [pid 1723:tid 3030367040] [client 192.227.223.108:443] Traceback (most recent call last):
[Wed Sep 30 11:49:34.563701 2020] [wsgi:error] [pid 1723:tid 3030367040] [client 192.227.223.108:443]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 11:49:34.563795 2020] [wsgi:error] [pid 1723:tid 3030367040] [client 192.227.223.108:443]     import cv2
[Wed Sep 30 11:49:34.563859 2020] [wsgi:error] [pid 1723:tid 3030367040] [client 192.227.223.108:443] ImportError: No module named cv2
[Wed Sep 30 12:24:12.827646 2020] [wsgi:error] [pid 1723:tid 2946440000] [client 196.52.43.109:36181] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 12:24:12.827758 2020] [wsgi:error] [pid 1723:tid 2946440000] [client 196.52.43.109:36181] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 12:24:12.827832 2020] [wsgi:error] [pid 1723:tid 2946440000] [client 196.52.43.109:36181] Traceback (most recent call last):
[Wed Sep 30 12:24:12.827904 2020] [wsgi:error] [pid 1723:tid 2946440000] [client 196.52.43.109:36181]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 12:24:12.827996 2020] [wsgi:error] [pid 1723:tid 2946440000] [client 196.52.43.109:36181]     import cv2
[Wed Sep 30 12:24:12.828062 2020] [wsgi:error] [pid 1723:tid 2946440000] [client 196.52.43.109:36181] ImportError: No module named cv2
[Wed Sep 30 12:46:36.951466 2020] [wsgi:error] [pid 1723:tid 2929654592] [client 193.118.55.146:52598] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 12:46:36.951572 2020] [wsgi:error] [pid 1723:tid 2929654592] [client 193.118.55.146:52598] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 12:46:36.951644 2020] [wsgi:error] [pid 1723:tid 2929654592] [client 193.118.55.146:52598] Traceback (most recent call last):
[Wed Sep 30 12:46:36.951715 2020] [wsgi:error] [pid 1723:tid 2929654592] [client 193.118.55.146:52598]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 12:46:36.951808 2020] [wsgi:error] [pid 1723:tid 2929654592] [client 193.118.55.146:52598]     import cv2
[Wed Sep 30 12:46:36.951872 2020] [wsgi:error] [pid 1723:tid 2929654592] [client 193.118.55.146:52598] ImportError: No module named cv2
[Wed Sep 30 12:53:47.751237 2020] [wsgi:error] [pid 1723:tid 3038759744] [client 27.7.163.216:35447] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 12:53:47.751339 2020] [wsgi:error] [pid 1723:tid 3038759744] [client 27.7.163.216:35447] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 12:53:47.751439 2020] [wsgi:error] [pid 1723:tid 3038759744] [client 27.7.163.216:35447] Traceback (most recent call last):
[Wed Sep 30 12:53:47.751507 2020] [wsgi:error] [pid 1723:tid 3038759744] [client 27.7.163.216:35447]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 12:53:47.751597 2020] [wsgi:error] [pid 1723:tid 3038759744] [client 27.7.163.216:35447]     import cv2
[Wed Sep 30 12:53:47.751660 2020] [wsgi:error] [pid 1723:tid 3038759744] [client 27.7.163.216:35447] ImportError: No module named cv2
[Wed Sep 30 13:18:37.231030 2020] [wsgi:error] [pid 1723:tid 2904476480] [client 129.41.86.1:43235] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 13:18:37.231135 2020] [wsgi:error] [pid 1723:tid 2904476480] [client 129.41.86.1:43235] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 13:18:37.231207 2020] [wsgi:error] [pid 1723:tid 2904476480] [client 129.41.86.1:43235] Traceback (most recent call last):
[Wed Sep 30 13:18:37.231279 2020] [wsgi:error] [pid 1723:tid 2904476480] [client 129.41.86.1:43235]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 13:18:37.231375 2020] [wsgi:error] [pid 1723:tid 2904476480] [client 129.41.86.1:43235]     import cv2
[Wed Sep 30 13:18:37.231440 2020] [wsgi:error] [pid 1723:tid 2904476480] [client 129.41.86.1:43235] ImportError: No module named cv2
[Wed Sep 30 13:41:31.109072 2020] [wsgi:error] [pid 1723:tid 2887691072] [client 129.41.86.1:58195] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 13:41:31.109178 2020] [wsgi:error] [pid 1723:tid 2887691072] [client 129.41.86.1:58195] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 13:41:31.109250 2020] [wsgi:error] [pid 1723:tid 2887691072] [client 129.41.86.1:58195] Traceback (most recent call last):
[Wed Sep 30 13:41:31.109321 2020] [wsgi:error] [pid 1723:tid 2887691072] [client 129.41.86.1:58195]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 13:41:31.109416 2020] [wsgi:error] [pid 1723:tid 2887691072] [client 129.41.86.1:58195]     import cv2
[Wed Sep 30 13:41:31.109480 2020] [wsgi:error] [pid 1723:tid 2887691072] [client 129.41.86.1:58195] ImportError: No module named cv2
[Wed Sep 30 14:56:16.206130 2020] [wsgi:error] [pid 1723:tid 2870905664] [client 114.225.229.27:10485] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 14:56:16.206238 2020] [wsgi:error] [pid 1723:tid 2870905664] [client 114.225.229.27:10485] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 14:56:16.206353 2020] [wsgi:error] [pid 1723:tid 2870905664] [client 114.225.229.27:10485] Traceback (most recent call last):
[Wed Sep 30 14:56:16.206429 2020] [wsgi:error] [pid 1723:tid 2870905664] [client 114.225.229.27:10485]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 14:56:16.206523 2020] [wsgi:error] [pid 1723:tid 2870905664] [client 114.225.229.27:10485]     import cv2
[Wed Sep 30 14:56:16.206589 2020] [wsgi:error] [pid 1723:tid 2870905664] [client 114.225.229.27:10485] ImportError: No module named cv2
[Wed Sep 30 15:34:19.362243 2020] [wsgi:error] [pid 1722:tid 2996796224] [client 192.241.233.240:38296] mod_wsgi (pid=1722): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 15:34:19.362379 2020] [wsgi:error] [pid 1722:tid 2996796224] [client 192.241.233.240:38296] mod_wsgi (pid=1722): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 15:34:19.362452 2020] [wsgi:error] [pid 1722:tid 2996796224] [client 192.241.233.240:38296] Traceback (most recent call last):
[Wed Sep 30 15:34:19.362553 2020] [wsgi:error] [pid 1722:tid 2996796224] [client 192.241.233.240:38296]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 15:34:19.362646 2020] [wsgi:error] [pid 1722:tid 2996796224] [client 192.241.233.240:38296]     import cv2
[Wed Sep 30 15:34:19.362707 2020] [wsgi:error] [pid 1722:tid 2996796224] [client 192.241.233.240:38296] ImportError: No module named cv2
[Wed Sep 30 16:47:06.927946 2020] [wsgi:error] [pid 1723:tid 3047152448] [client 141.101.229.15:58880] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 16:47:06.928051 2020] [wsgi:error] [pid 1723:tid 3047152448] [client 141.101.229.15:58880] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 16:47:06.928121 2020] [wsgi:error] [pid 1723:tid 3047152448] [client 141.101.229.15:58880] Traceback (most recent call last):
[Wed Sep 30 16:47:06.928191 2020] [wsgi:error] [pid 1723:tid 3047152448] [client 141.101.229.15:58880]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 16:47:06.928285 2020] [wsgi:error] [pid 1723:tid 3047152448] [client 141.101.229.15:58880]     import cv2
[Wed Sep 30 16:47:06.928349 2020] [wsgi:error] [pid 1723:tid 3047152448] [client 141.101.229.15:58880] ImportError: No module named cv2
[Wed Sep 30 16:53:24.790313 2020] [wsgi:error] [pid 1723:tid 3063937856] [client 192.168.1.107:40710] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 16:53:24.790404 2020] [wsgi:error] [pid 1723:tid 3063937856] [client 192.168.1.107:40710] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'.
[Wed Sep 30 16:53:24.790476 2020] [wsgi:error] [pid 1723:tid 3063937856] [client 192.168.1.107:40710] Traceback (most recent call last):
[Wed Sep 30 16:53:24.790553 2020] [wsgi:error] [pid 1723:tid 3063937856] [client 192.168.1.107:40710]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>
[Wed Sep 30 16:53:24.790648 2020] [wsgi:error] [pid 1723:tid 3063937856] [client 192.168.1.107:40710]     import cv2
[Wed Sep 30 16:53:24.790714 2020] [wsgi:error] [pid 1723:tid 3063937856] [client 192.168.1.107:40710] ImportError: No module named cv2
[Wed Sep 30 16:53:25.455612 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 192.168.1.107:40712] mod_wsgi (pid=1723): Failed to exec Python script file '/var/www/capfireapp/python-app/controller.py'., referer: http://192.168.1.68/
[Wed Sep 30 16:53:25.455672 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 192.168.1.107:40712] mod_wsgi (pid=1723): Exception occurred processing WSGI script '/var/www/capfireapp/python-app/controller.py'., referer: http://192.168.1.68/
[Wed Sep 30 16:53:25.455733 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 192.168.1.107:40712] Traceback (most recent call last):, referer: http://192.168.1.68/
[Wed Sep 30 16:53:25.455796 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 192.168.1.107:40712]   File "/var/www/capfireapp/python-app/controller.py", line 1, in <module>, referer: http://192.168.1.68/
[Wed Sep 30 16:53:25.455876 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 192.168.1.107:40712]     import cv2, referer: http://192.168.1.68/
[Wed Sep 30 16:53:25.455936 2020] [wsgi:error] [pid 1723:tid 3005188928] [client 192.168.1.107:40712] ImportError: No module named cv2, referer: http://192.168.1.68/
[Wed Sep 30 18:07:05.333049 2020] [wsgi:error] [pid 1722:tid 2963225408] [client 103.145.13.24:47748] mod_wsgi (pid=1722): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
[Wed Sep 30 18:19:22.569778 2020] [wsgi:error] [pid 1723:tid 2971618112] [client 172.98.72.137:48700] mod_wsgi (pid=1723): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
[Wed Sep 30 18:26:03.381573 2020] [wsgi:error] [pid 1722:tid 2954832704] [client 192.35.168.251:52960] mod_wsgi (pid=1722): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
[Wed Sep 30 18:26:03.535303 2020] [wsgi:error] [pid 1723:tid 3030367040] [client 192.35.168.251:38990] mod_wsgi (pid=1723): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
[Wed Sep 30 18:30:02.451005 2020] [wsgi:error] [pid 1722:tid 2938047296] [client 27.216.40.147:40934] mod_wsgi (pid=1722): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
[Wed Sep 30 19:22:00.893886 2020] [wsgi:error] [pid 1723:tid 2946440000] [client 34.208.128.240:41028] mod_wsgi (pid=1723): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
[Wed Sep 30 19:33:35.161471 2020] [wsgi:error] [pid 1722:tid 2929654592] [client 31.192.137.109:37537] mod_wsgi (pid=1722): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
[Wed Sep 30 20:01:07.616686 2020] [wsgi:error] [pid 1723:tid 2929654592] [client 168.167.52.182:52695] mod_wsgi (pid=1723): Target WSGI script '/var/www/capfireapp/python-app/controller.py' does not contain WSGI application 'application'.
